# Generated by Django 3.2 on 2021-07-11 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='terraria_search.category')),
            ],
        ),
        migrations.CreateModel(
            name='NeededMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('how_to_get', models.TextField(blank=True)),
                ('category', models.ManyToManyField(related_name='item', to='terraria_search.Category')),
                ('childcategory', models.ManyToManyField(related_name='item', to='terraria_search.ChildCategory')),
                ('needed_material_for_item', models.ManyToManyField(blank=True, related_name='item', to='terraria_search.NeededMaterial')),
                ('parentCategory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='terraria_search.parentcategory')),
                ('workplace_for_item', models.ManyToManyField(blank=True, related_name='item', to='terraria_search.WorkPlace')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='parentCategory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='terraria_search.parentcategory'),
        ),
    ]
