# Generated by Django 3.2 on 2021-06-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('needed_furniture', models.CharField(max_length=255)),
                ('needed_material', models.CharField(max_length=255)),
                ('how_to_get', models.TextField()),
            ],
        ),
    ]
