# Generated by Django 3.2 on 2021-06-29 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terraria_search', '0002_auto_20210629_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='needed_furniture',
            new_name='workplace',
        ),
    ]
