# Generated by Django 3.2.4 on 2021-06-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraria_search', '0003_rename_needed_furniture_items_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
