# Generated by Django 3.2.4 on 2021-06-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraria_search', '0006_alter_parentcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='items',
            name='image',
        ),
        migrations.RemoveField(
            model_name='parentcategory',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
