# Generated by Django 3.2 on 2021-07-02 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terraria_search', '0007_auto_20210630_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='terraria_search.category')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='childcategory',
            field=models.ManyToManyField(related_name='item', to='terraria_search.ChildCategory'),
        ),
    ]
