# Generated by Django 3.2 on 2021-07-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraria_search', '0010_auto_20210705_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='needed_material_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='workplace_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
