# Generated by Django 3.2 on 2021-07-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraria_search', '0011_auto_20210706_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='needed_material',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='workplace',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
