# Generated by Django 3.2 on 2021-07-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraria_search', '0012_auto_20210706_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='how_to_get',
            field=models.TextField(blank=True),
        ),
    ]
