# Generated by Django 3.2 on 2021-07-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraria_search', '0014_auto_20210707_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_needed_material',
            field=models.ManyToManyField(blank=True, null=True, related_name='_terraria_search_items_item_needed_material_+', to='terraria_search.Items'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_workplace',
            field=models.ManyToManyField(blank=True, null=True, related_name='_terraria_search_items_item_workplace_+', to='terraria_search.Items'),
        ),
    ]
